version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci/cd"

  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - "chore"
      - "python:uv"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
        update-types:
          - "minor"
          - "patch"

      other-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "@angular/*"
          - "@angular-devkit/*"

    ignore:
      - dependency-name: "@angular/*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@angular-devkit/*"
        update-types:
          - "version-update:semver-major"

    labels:
      - "chore"
      - "typescript"

  - package-ecosystem: "docker"
    directories:
      - "/backend"
      - "/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "chore"
      - "docker"
