# FIRST STAGE: Build the Angular Application
FROM node:22.6.1 as build

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the working directory
COPY . .

# Update lock file
RUN npm install

# Install dependencies
RUN npm ci

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Build the Angular application
RUN ng build --configuration=development

# SECOND STAGE: Serve the application using Nginx
FROM docker.io/library/nginx:1.26.0

# Copy the built application from the previous stage
COPY --from=build /app/dist/pdataviewer/browser /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx serve
CMD ["nginx", "-g", "daemon off;"]
